spring.application.name=bookatividade

# URL de conexão: troque 'nome_do_seu_banco' pelo nome real do banco no Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/bookauction

# Seu usuário do Postgres (geralmente é 'postgres')
spring.datasource.username=postgres

# Sua senha do Postgres
spring.datasource.password=ifpb

# Driver do PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações extras do Hibernate (ajuda a criar as tabelas automaticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect